apiVersion: v2
name       : App-HelmChart
description: My Helm chart for Kubernetes
type       : application
version    : 3.9.1   # This is the Helm Chart version
appVersion : "1.2.3" # This is the version of the application being deployed

keywords:
  - apache
  - http
  - https
  - artemgurianov

maintainers:
  - name : Artem Gurianov
    email: tt@tt.tt
    url  : yandex.ru